hyperparameters:
  batch_size: 32
  learning_rate: 0.001
  num_epochs: 100
  dropout_rate: 0.5
  weight_decay: 0.0001
  momentum: 0.9

model:
  input_size: 784
  hidden_size: 128
  output_size: 10
  num_layers: 2
  activation_function: "ReLU"

optimizer:
  type: "Adam"
  beta1: 0.9
  beta2: 0.999
  eps: 1e-08

scheduler:
  step_size: 10
  gamma: 0.1

loss_function: "MSELoss"

data_augmentation:
  rotation_range: 10
  width_shift_range: 0.1
  height_shift_range: 0.1
  horizontal_flip: True

evaluation_metrics:
  - accuracy
  - precision
  - recall
  - f1_score