model:
  name: "Luna"
  type: "CA"
  input_size: 784
  hidden_size: 128
  output_size: 10
  num_layers: 2
  learning_rate: 0.001
  batch_size: 32
  epochs: 100
  activation_function: "ReLU"
  optimizer: "Adam"
  loss_function: "MSELoss"

training:
  train_test_split: 0.8
  shuffle: True
  random_seed: 42

data:
  path: "data/"
  train_data: "training_data.npy"
  test_data: "test_data.npy"
  labels: "labels.npy"

evaluation:
  metrics: ["accuracy", "precision", "recall", "f1_score"]

logging:
  log_interval: 10
  save_model: True
  save_path: "results/models/"